Repository nimblehq/nimble-medium-ios, pull requests merged in 2021-08, with the labels that each got.

#5 [#1] [Chore] Setup project - Part 1
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/chore_template.md
  .github/ISSUE_TEMPLATE/feature_template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  install.sh
  resources/git-hooks/pre-push
  resources/images/project-config/default-build-configurations.png
  resources/images/project-config/default-configurations.png
  resources/images/project-config/default-custom-flags.png
  resources/images/project-config/default-dsym.png
  resources/images/readme/configuration_custom-attributes.png
  resources/images/readme/configuration_default-attributes.png
  resources/images/readme/configuration_result.png
  resources/images/readme/configurations_remove-default-configurations.png
  resources/images/readme/scheme_add-targets-uuid-to-blueprint-identifier.png
  resources/images/readme/scheme_remove-folder.png
  resources/images/readme/scheme_result.png
  resources/images/readme/scheme_targets-auto-generated-uuid.png
  resources/xcode-code-snippets/unit-test/unit-test-context.codesnippet
  resources/xcode-code-snippets/unit-test/unit-test-interactor-it-trigger.codesnippet
  resources/xcode-code-snippets/unit-test/unit-test-it.codesnippet
  resources/xcode-code-snippets/unit-test/unit-test-presenter-it-call.codesnippet
  resources/xcode-code-snippets/unit-test/unit-test-router-it-present.codesnippet
  resources/xcode-code-snippets/unit-test/unit-test-router-itpush.codesnippet
  resources/xcode-code-snippets/unit-test/unit-test-swiftlint-headline-disable.codesnippet
  resources/xcode-templates/App.xctemplate/Gemfile
  resources/xcode-templates/App.xctemplate/Podfile
  resources/xcode-templates/App.xctemplate/TemplateIcon.png
  resources/xcode-templates/App.xctemplate/TemplateIcon@2x.png
  resources/xcode-templates/App.xctemplate/TemplateInfo.plist
  resources/xcode-templates/App.xctemplate/___PACKAGENAME___ Staging.xcscheme
  resources/xcode-templates/App.xctemplate/___PACKAGENAME___ UAT.xcscheme
  resources/xcode-templates/App.xctemplate/___PACKAGENAME___.xcscheme
  resources/xcode-templates/App.xctemplate/fastlane/Constants/Constants.rb
  resources/xcode-templates/App.xctemplate/fastlane/Fastfile
  resources/xcode-templates/App.xctemplate/fastlane/Managers/CodeSigningManager.rb
  resources/xcode-templates/App.xctemplate/fastlane/Managers/TestManager.rb
  resources/xcode-templates/Cocoa Touch App Base.xctemplate/Assets.xcassets/AccentColor.colorset/Contents.json
  resources/xcode-templates/Cocoa Touch App Base.xctemplate/Assets.xcassets/Contents.json
  resources/xcode-templates/Cocoa Touch App Base.xctemplate/LaunchScreen.storyboard
  resources/xcode-templates/Cocoa Touch App Base.xctemplate/TemplateInfo.plist
  scripts/colors.sh
  scripts/helpers.sh
Labels: type : chore

#13 [#1] [Chore] Setup project - Part 2 (re-merge)
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  NimbleMedium.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  NimbleMedium.xcodeproj/xcshareddata/xcschemes/NimbleMedium Staging.xcscheme
  NimbleMedium.xcodeproj/xcshareddata/xcschemes/NimbleMedium.xcscheme
  NimbleMedium/App.swift
  NimbleMedium/Info.plist
  NimbleMedium/Modules/Home/HomeView.swift
  NimbleMedium/Preview Content/Preview Assets.xcassets/Contents.json
  NimbleMedium/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  NimbleMedium/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  NimbleMedium/Resources/Assets.xcassets/Contents.json
  NimbleMediumTests/Info.plist
  NimbleMediumTests/NimbleMediumTests.swift
  NimbleMediumUITests/Info.plist
  NimbleMediumUITests/NimbleMediumUITests.swift
Labels: type : chore

#9 [#1] [Chore] Setup project - Final
  .swiftlint.yml
  Gemfile
  Gemfile.lock
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium.xcworkspace/contents.xcworkspacedata
  NimbleMedium.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  NimbleMedium/App.swift
  NimbleMediumTests/NimbleMediumTests.swift
  NimbleMediumUITests/NimbleMediumUITests.swift
  Podfile
  Podfile.lock
  README.md
Labels: type : chore

#14 [#2] [Chore] Setup CI
  .github/workflows/lint_and_unit_test.yml
  NimbleMedium.xcodeproj/project.pbxproj
Labels: type : chore

#25 [#20] Setup project localization
  .gitignore
  .swiftlint.yml
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Modules/Home/HomeView.swift
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Supports/Helpers/Typealias.swift
  Podfile
  Podfile.lock
Labels: type : chore

#35 [#34] [Chore] Refactor project structure
  .gitignore
  .swiftlint.yml
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Configurations/Info.plist
  NimbleMedium/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  NimbleMedium/Sources/Application/App.swift
  NimbleMedium/Sources/Constants/Constants.swift
  NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
  NimbleMedium/Sources/Supports/Helpers/Typealias.swift
  NimbleMediumTests/Configurations/Info.plist
  NimbleMediumTests/NimbleMediumTests.swift
  NimbleMediumUITests.swift
  NimbleMediumUITests/Configurations/Info.plist
Labels: type : chore

#36 [#7] Create default top navigation bar
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Constants/Constant+String.swift
  NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
  NimbleMedium/Sources/Supports/Extensions/SwiftUI/Color+UIColor.swift
  NimbleMedium/Sources/Supports/Extensions/SwiftUI/View+NavigationBar.swift
Labels: type : feature, category : ui

#43 [#34] Add empty folders
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Data/Keychain/.gitkeep
  NimbleMedium/Sources/Data/NetworkAPI/.gitkeep
  NimbleMedium/Sources/Data/Repositories/.gitkeep
  NimbleMedium/Sources/Domain/Entities/.gitkeep
  NimbleMedium/Sources/Domain/UseCases/.gitkeep
  NimbleMedium/Sources/Presentation/Views/.gitkeep
  NimbleMedium/Sources/Supports/Extensions/Foundation/.gitkeep
  NimbleMedium/Sources/Supports/Extensions/UIKit/.gitkeep
  NimbleMediumTests/Resources/.gitkeep
  NimbleMediumTests/Sources/Dummy/Data/Models/.gitkeep
  NimbleMediumTests/Sources/Dummy/Domain/Entities/.gitkeep
  NimbleMediumTests/Sources/Dummy/Modules/.gitkeep
  NimbleMediumTests/Sources/Mocks/.gitkeep
  NimbleMediumTests/Sources/Specs/Data/Repositories/.gitkeep
  NimbleMediumTests/Sources/Specs/Domain/UseCases/.gitkeep
  NimbleMediumTests/Sources/Specs/Presentation/Modules/.gitkeep
  NimbleMediumTests/Sources/Specs/Supports/Extensions/.gitkeep
  NimbleMediumTests/Sources/Utilities/.gitkeep
  NimbleMediumUITests/NimbleMediumUITests.swift
  NimbleMediumUITests/Resources/.gitkeep
  NimbleMediumUITests/Sources/AccessibilityIdentifiers/.gitkeep
  NimbleMediumUITests/Sources/Flows/.gitkeep
  NimbleMediumUITests/Sources/Screens/.gitkeep
  NimbleMediumUITests/Sources/Specs/.gitkeep
  NimbleMediumUITests/Sources/Utilities/.gitkeep
Labels: type : chore

#44 [#6] Create left navigation menu - Part I
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Resources/Assets.xcassets/Navigation/Contents.json
  NimbleMedium/Resources/Assets.xcassets/Navigation/menu-icon.imageset/Contents.json
  NimbleMedium/Resources/Assets.xcassets/Navigation/menu-icon.imageset/nav-menu-btn.pdf
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
  NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
Labels: type : feature, category : ui

#45 [#6] Create left navigation menu - Final
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuView.swift
Labels: type : feature, category : ui

#51 [#37] Integrate left navigation menu - Part I
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Application/App.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
  NimbleMedium/Sources/Presentation/Modules/Home/HomeViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuView.swift
  NimbleMedium/Sources/Supports/Extensions/SwiftUI/View+RxDriver.swift
  NimbleMedium/Sources/Supports/Helpers/Rx/BehaviorRelayProperty.swift
  NimbleMedium/Sources/Supports/Helpers/Rx/PublishRelayProperty.swift
  Podfile
  Podfile.lock
Labels: type : feature, category: integration

#109 [#10] As a user, I can login from the left menu
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Resources/Assets.xcassets/Menu/Contents.json
  NimbleMedium/Resources/Assets.xcassets/Menu/icon-login.imageset/Contents.json
  NimbleMedium/Resources/Assets.xcassets/Menu/icon-login.imageset/icons8-login-50.png
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Constants/Constants+String.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/MenuOptionButtonStyle.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActionsView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuView.swift
Labels: type : feature, category : ui

#112 [#11] As a user, I can view the default left menu header when not logged in
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeaderView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuView.swift
Labels: type : feature, category : ui

#110 [#12] As a user, I can signup from the left menu
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Resources/Assets.xcassets/Menu/icon-signup.imageset/Contents.json
  NimbleMedium/Resources/Assets.xcassets/Menu/icon-signup.imageset/user-signup-3058.png
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Presentation/Modules/SideMenu/MenuOptionButtonStyle.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActionItemView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActionsView.swift
Labels: type : feature, category : ui

#113 [#24] As a user, I can login to the application
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
  NimbleMedium/Sources/Presentation/Modules/Login/LoginView.swift
  NimbleMedium/Sources/Presentation/Modules/Login/LoginViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActionItemView.swift
Labels: category : ui, priority : medium

#115 [#27] As a user, I can login from the left menu
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Application/App.swift
  NimbleMedium/Sources/Factories/Application/DependencyFactory+ViewModelFactoryProtocol.swift
  NimbleMedium/Sources/Factories/Application/DependencyFactory.swift
  NimbleMedium/Sources/Factories/Presentation/ViewModelFactoryProtocol.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
  NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
  NimbleMedium/Sources/Presentation/Modules/Home/HomeViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Login/LoginView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/MenuOptionButtonStyle.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionItemView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuMain/SideMenuView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuMain/SideMenuViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuView.swift
  NimbleMedium/Sources/Presentation/Modules/Signup/SignupView.swift
  NimbleMedium/Sources/Presentation/Views/Background.swift
Labels: category: integration, priority : medium

#118 [#32] As a user, I can login to the application
  Gemfile.lock
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Application/App.swift
  NimbleMedium/Sources/Constants/Constants+API.swift
  NimbleMedium/Sources/Constants/Constants.swift
  NimbleMedium/Sources/Data/NetworkAPI/Core/NetworkAPIProtocol.swift
  NimbleMedium/Sources/Data/NetworkAPI/Core/RequestConfiguration.swift
  NimbleMedium/Sources/Data/NetworkAPI/Models/APIUser.swift
  NimbleMedium/Sources/Data/NetworkAPI/NetworkAPI.swift
  NimbleMedium/Sources/Data/NetworkAPI/RequestConfigurations/AuthRequestConfiguration.swift
  NimbleMedium/Sources/Data/Repositories/Auth/AuthRepository.swift
  NimbleMedium/Sources/Domain/Entities/User.swift
  NimbleMedium/Sources/Domain/Repositories/Auth/AuthRepositoryProtocol.swift
  NimbleMedium/Sources/Domain/UseCases/LoginUseCase.swift
  NimbleMedium/Sources/Factories/Application/DependencyFactory+UseCaseFactoryProtocol.swift
  NimbleMedium/Sources/Factories/Application/DependencyFactory.swift
  NimbleMedium/Sources/Factories/Data/RepositoryFactoryProtocol.swift
  NimbleMedium/Sources/Factories/Domain/UseCaseFactoryProtocol.swift
  NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuMain/SideMenuView.swift
  NimbleMedium/Sources/Supports/Extensions/Foundation/JSONDecoder+Default.swift
  Podfile
  Podfile.lock
Labels: category : backend, priority : medium

#119 [Chore] Add Debug configuration for Staging and Production schemes
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium.xcodeproj/xcshareddata/xcschemes/NimbleMedium Staging.xcscheme
  NimbleMedium.xcodeproj/xcshareddata/xcschemes/NimbleMedium.xcscheme
  Podfile.lock
Labels: priority : high, type : chore

#116 [#26] As a user, I can signup from the left menu
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Factories/Application/DependencyFactory+ViewModelFactoryProtocol.swift
  NimbleMedium/Sources/Factories/Presentation/ViewModelFactoryProtocol.swift
  NimbleMedium/Sources/Presentation/Modules/Login/LoginView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuMain/SideMenuViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Signup/SignupView.swift
  NimbleMedium/Sources/Presentation/Views/AppMainButton.swift
  NimbleMedium/Sources/Presentation/Views/AuthSecureFieldView.swift
  NimbleMedium/Sources/Presentation/Views/AuthTextFieldView.swift
Labels: category: integration, priority : medium
