Repository nimblehq/nimble-medium-ios, pull requests merged in 2021-10, with the labels that each got.

#159 [66] As a user, I can see the list of created articles from the profile screen
  Gemfile
  Gemfile.lock
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Domain/UseCases/Article/GetCreatedArticlesUseCase.swift
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMediumTests/Sources/Specs/Domain/UseCases/Article/GetCreatedArticlesUseCaseSpec.swift
Labels: category : backend

#164 [Chore] Refactor Login and Sign ViewModels and add mapToVoid extension
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Constants/Constants+API.swift
  NimbleMedium/Sources/Domain/UseCases/Auth/LoginUseCase.swift
  NimbleMedium/Sources/Domain/UseCases/Auth/SignupUseCase.swift
  NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentsViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/FeedDetail/FeedDetailViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Login/LoginViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Signup/SignupViewModel.swift
  NimbleMedium/Sources/Supports/Extensions/Rx/ObservableType+Void.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/Login/LoginViewModelSpec.swift
Labels: type : chore, priority : medium

#165 [#64] As a user, I can view other author profile details from the article details screen when not logged in
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView+UIModel.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileViewModel.swift
  NimbleMedium/Sources/Presentation/Views/AuthorView.swift
  NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/UserProfile/UserProfileViewModelSpec.swift
Labels: priority : high, type : feature, category: integration

#163 [#69] As a user, I can see the list of favorited articles from the profile screen when not logged
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentRow/FeedCommentRow.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRow.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderView.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/ArticleList/UserProfileView+ArticleList.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView+TabItemTitle.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView.swift
  NimbleMedium/Sources/Presentation/Views/AuthorView.swift
  NimbleMedium/Sources/Presentation/Views/AvatarView.swift
  Podfile
  Podfile.lock
Labels: category : ui

#171 Renaming FeedComments to ArticleComments
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Domain/UseCases/Comment/GetArticleCommentsUseCase.swift
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentRow/ArticleCommentRow+UIModel.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentRow/ArticleCommentRow.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentRow/ArticleCommentRowViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentsView.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentsViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift
  NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentRow/FeedCommentRowViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentsViewModel.swift
  NimbleMediumTests/Sources/Specs/Domain/UseCases/Comment/GetArticleCommentsUseCaseSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/ArticleComments/ArticleCommentsViewModelSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/ArticleComments/FeedCommentRow/ArticleCommentRowViewModelSpec.swift
Labels: priority : high, type : chore

#174 [#57] As a user, I can view my own profile details
  NimbleMedium/Sources/Domain/Repositories/User/UserSessionRepositoryProtocol.swift
  NimbleMedium/Sources/Domain/UseCases/User/GetCurrentUserUseCase.swift
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuMain/SideMenuViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileViewModel.swift
  NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
  NimbleMediumTests/Sources/Specs/Domain/UseCases/User/GetCurrentUserUseCaseSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/UserProfile/UserProfileViewModelSpec.swift
Labels: type : feature, category: integration

#169 [#65] As a user, I can see the list of created articles from the profile screen when not logged in
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Presentation/Modules/UserProfile/ArticleList/UserProfileView+ArticleList.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView.swift
Labels: category : ui

#175 [#167] Fix: 1 nokogiri vulnerability found in Gemfile.lock
  Gemfile.lock
Labels: type : bug, priority : medium

#182 [#39] As a user, I can update my profile from the left menu header
  NimbleMedium/Sources/Constants/SystemImageName.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderView.swift
Labels: type : feature, category : ui

#183 [#50] As a user, I can toggle to update my follow status of another user from the article details screen
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift
  NimbleMedium/Sources/Presentation/Views/FollowButton.swift
Labels: category : ui

#184 [#72] Add Follow Button intto Profile screen
  NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView.swift
  NimbleMedium/Sources/Presentation/Views/FollowButton.swift
Labels: category : ui

#185 [#42] As a user, I can logout from the left menu
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Data/Repositories/User/UserSessionRepository.swift
  NimbleMedium/Sources/Domain/Repositories/User/UserSessionRepositoryProtocol.swift
  NimbleMedium/Sources/Domain/UseCases/Auth/LogoutUseCase.swift
  NimbleMedium/Sources/Domain/UseCases/User/GetCurrentSessionUseCase.swift
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMedium/Sources/Presentation/Modules/Login/LoginView.swift
  NimbleMedium/Sources/Presentation/Modules/Login/LoginViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuMain/SideMenuViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Signup/SignupView.swift
  NimbleMedium/Sources/Presentation/Modules/Signup/SignupViewModel.swift
  NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
  NimbleMediumTests/Sources/Specs/Domain/UseCases/Auth/LogoutUseCaseSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModelSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderViewModelSpec.swift
Labels: type : feature, category: integration

#187 [#73] As a user, I can follow another user
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Application/App.swift
  NimbleMedium/Sources/Data/NetworkAPI/RequestConfigurations/UserRequestConfiguration.swift
  NimbleMedium/Sources/Data/Repositories/User/UserRepository.swift
  NimbleMedium/Sources/Domain/Repositories/User/UserRepositoryProtocol.swift
  NimbleMedium/Sources/Domain/UseCases/User/FollowUserUseCase.swift
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMediumTests/Sources/Specs/Domain/UseCases/User/FollowUserUseCaseSpec.swift
Labels: category : backend

#189 [#58] As a user, I can update my own profile details
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Data/NetworkAPI/RequestConfigurations/AuthRequestConfiguration.swift
  NimbleMedium/Sources/Data/Repositories/Auth/AuthRepository.swift
  NimbleMedium/Sources/Domain/Parameters/UpdateCurrentUserParameters.swift
  NimbleMedium/Sources/Domain/Repositories/Auth/AuthRepositoryProtocol.swift
  NimbleMedium/Sources/Domain/UseCases/Auth/GetCurrentUserUseCase.swift
  NimbleMedium/Sources/Domain/UseCases/Auth/UpdateCurrentUserUseCase.swift
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMediumTests/Sources/Dummy/Data/Models/UpdateCurrentUserParameters+Dummy.swift
  NimbleMediumTests/Sources/Specs/Domain/UseCases/Auth/GetCurrentUserUseCaseSpec.swift
  NimbleMediumTests/Sources/Specs/Domain/UseCases/Auth/UpdateCurrentUserUseCaseSpec.swift
Labels: type : feature, category : backend

#190 [#61] As a user, I can update my own profile details
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMedium/Sources/Presentation/Modules/EditProfile/EditProfileView+UIModel.swift
  NimbleMedium/Sources/Presentation/Modules/EditProfile/EditProfileView.swift
  NimbleMedium/Sources/Presentation/Modules/EditProfile/EditProfileViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuMain/SideMenuView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuMain/SideMenuViewModel.swift
  NimbleMedium/Sources/Presentation/Views/AppTextView.swift
  NimbleMedium/Sources/Supports/Extensions/Foundation/JSONDecoder+Default.swift
  NimbleMedium/Sources/Supports/Extensions/Foundation/String+EmptyCheck.swift
  NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/EditProfile/EditProfileViewModelSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/SideMenu/SideMenuMain/SideMenuViewModelSpec.swift
Labels: type : feature, category: integration

#196 [#81] As a user, I can create a new article
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Data/NetworkAPI/RequestConfigurations/ArticleRequestConfiguration.swift
  NimbleMedium/Sources/Data/NetworkAPI/RequestConfigurations/AuthRequestConfiguration.swift
  NimbleMedium/Sources/Data/Repositories/Article/ArticleRepository.swift
  NimbleMedium/Sources/Domain/Parameters/CreateArticleParameters.swift
  NimbleMedium/Sources/Domain/Parameters/UpdateCurrentUserParameters.swift
  NimbleMedium/Sources/Domain/Repositories/Article/ArticleRepositoryProtocol.swift
  NimbleMedium/Sources/Domain/UseCases/Article/CreateArticleUseCase.swift
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMedium/Sources/Supports/Extensions/Foundation/Encodable+Dictionary.swift
  NimbleMediumTests/Sources/Dummy/Data/Models/CreateArticleParameters+Dummy.swift
  NimbleMediumTests/Sources/Specs/Data/Repositories/Article/ArticleRepositorySpec.swift
  NimbleMediumTests/Sources/Specs/Domain/UseCases/Article/CreateArticleUseCaseSpec.swift
Labels: type : feature, category : backend
