Repository nimblehq/nimble-medium-ios, pull requests merged in 2021-09, with the labels that each got.

#93 [#3] Setup CD pipeline (staging) - Final
  .github/workflows/deploy_staging.yml
  Gemfile
  Gemfile.lock
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Configurations/Plists/Info.plist
  fastlane/Appfile
  fastlane/Constants/Constants.rb
  fastlane/Fastfile
  fastlane/Gymfile
  fastlane/Managers/BuildManager.rb
  fastlane/Managers/DistributionManager.rb
  fastlane/Managers/SymbolManager.rb
  fastlane/Managers/VersioningManager.rb
  fastlane/Matchfile
  fastlane/Pluginfile
Labels: type : chore

#111 [#4] Set up CD pipeline for production releases
  .github/workflows/deploy_testflight.yml
  NimbleMedium.xcodeproj/project.pbxproj
Labels: type : chore

#121 [#30] As a user, I can login to the application
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Application/App.swift
  NimbleMedium/Sources/Data/Keychain/Keychain.swift
  NimbleMedium/Sources/Data/Keychain/KeychainKey.swift
  NimbleMedium/Sources/Data/NetworkAPI/Core/NetworkAPI.swift
  NimbleMedium/Sources/Data/NetworkAPI/Models/APIUser.swift
  NimbleMedium/Sources/Data/NetworkAPI/Models/APIUserResponse.swift
  NimbleMedium/Sources/Data/NetworkAPI/Models/CodableUser.swift
  NimbleMedium/Sources/Data/Repositories/Auth/AuthRepository.swift
  NimbleMedium/Sources/Data/Repositories/User/UserSessionRepository.swift
  NimbleMedium/Sources/Domain/Repositories/User/UserSessionRepositoryProtocol.swift
  NimbleMedium/Sources/Domain/UseCases/LoginUseCase.swift
  NimbleMedium/Sources/Factories/Application/DependencyFactory+UseCaseFactoryProtocol.swift
  NimbleMedium/Sources/Factories/Application/DependencyFactory+ViewModelFactoryProtocol.swift
  NimbleMedium/Sources/Factories/Application/DependencyFactory.swift
  NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
  NimbleMedium/Sources/Presentation/Modules/Login/LoginView.swift
  NimbleMedium/Sources/Presentation/Modules/Login/LoginViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuMain/SideMenuView.swift
  NimbleMedium/Sources/Supports/Extensions/SwiftUI/View+OnReceive.swift
Labels: category: integration, priority : medium

#122 [Chore] Write unit test for LoginViewModel
  .github/workflows/lint_and_unit_test.yml
  .gitignore
  .sourcery.yml
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Domain/UseCases/LoginUseCase.swift
  NimbleMedium/Sources/Factories/Application/DependencyFactory.swift
  NimbleMediumTests/.swiftlint.yml
  NimbleMediumTests/NimbleMediumTests.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/Login/LoginViewModelSpec.swift
  NimbleMediumTests/Sources/Utilities/TestError.swift
  tools/sourcery/templates/AutoMockable.stencil
Labels: priority : low

#123 [#33] As a user, I can signup for a new account
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Data/NetworkAPI/RequestConfigurations/AuthRequestConfiguration.swift
  NimbleMedium/Sources/Data/Repositories/Auth/AuthRepository.swift
  NimbleMedium/Sources/Domain/Repositories/Auth/AuthRepositoryProtocol.swift
  NimbleMedium/Sources/Domain/UseCases/SignupUseCase.swift
  NimbleMedium/Sources/Factories/Application/DependencyFactory+UseCaseFactoryProtocol.swift
  NimbleMedium/Sources/Factories/Domain/UseCaseFactoryProtocol.swift
Labels: category : backend, priority : medium

#129 [#126] Setup Codecov
  .github/workflows/deploy_staging.yml
  .swiftlint.yml
Labels: type : chore

#124 [#31] As a user, I can signup for a new account
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Factories/Application/DependencyFactory+ViewModelFactoryProtocol.swift
  NimbleMedium/Sources/Presentation/Modules/Login/LoginView.swift
  NimbleMedium/Sources/Presentation/Modules/Login/LoginViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Signup/SignupView.swift
  NimbleMedium/Sources/Presentation/Modules/Signup/SignupViewModel.swift
Labels: category: integration, priority : medium

#125 [#15] [UI] As a user, I can see the global feeds from the home screen when not logged in
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NimbleMedium/Resources/Assets.xcassets/Profile/Contents.json
  NimbleMedium/Resources/Assets.xcassets/Profile/default-avatar.imageset/Contents.json
  NimbleMedium/Resources/Assets.xcassets/Profile/default-avatar.imageset/default-avatar.pdf
  NimbleMedium/Sources/Domain/Entities/Article.swift
  NimbleMedium/Sources/Domain/Entities/Profile.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRow.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
  NimbleMedium/Sources/Supports/Extensions/Foundation/DateFormatter+Formats.swift
Labels: category : ui

#128 [#16] [Backend] As a user, I can see the global feeds from the home screen
  .swiftlint.yml
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NimbleMedium/Sources/Constants/Constants.swift
  NimbleMedium/Sources/Data/NetworkAPI/Models/APIArticleResponse.swift
  NimbleMedium/Sources/Data/NetworkAPI/Models/DecodableArticle.swift
  NimbleMedium/Sources/Data/NetworkAPI/Models/DecodableProfile.swift
  NimbleMedium/Sources/Data/NetworkAPI/RequestConfigurations/ArticleRequestConfiguration.swift
  NimbleMedium/Sources/Data/Repositories/Article/ArticleRepository.swift
  NimbleMedium/Sources/Domain/Repositories/Article/ArticleRepositoryProtocol.swift
  NimbleMedium/Sources/Domain/UseCases/ListArticlesUseCase.swift
  NimbleMedium/Sources/Factories/Application/DependencyFactory+UseCaseFactoryProtocol.swift
  NimbleMedium/Sources/Factories/Application/DependencyFactory.swift
  NimbleMedium/Sources/Factories/Data/RepositoryFactoryProtocol.swift
  NimbleMedium/Sources/Factories/Domain/UseCaseFactoryProtocol.swift
  NimbleMedium/Sources/Supports/Extensions/Foundation/DateFormatter+Formats.swift
  NimbleMedium/Sources/Supports/Extensions/Foundation/JSONDecoder+Default.swift
  NimbleMediumTests/Resources/JSON/articles.json
  NimbleMediumTests/Sources/Dummy/Data/Models/.swiftlint.yml
  NimbleMediumTests/Sources/Dummy/Data/Models/APIArticleResponse+Dummy.swift
  NimbleMediumTests/Sources/Mocks/Data/NetworkAPIProtocolMock.swift
  NimbleMediumTests/Sources/Specs/Data/Repositories/ArticleRepositorySpec.swift
  NimbleMediumTests/Sources/Specs/Domain/UseCases/ListArticlesUseCaseSpec.swift
  NimbleMediumTests/Sources/Utilities/Data+Decode.swift
  NimbleMediumTests/Sources/Utilities/FileResource+Decode.swift
Labels: category : backend

#131 [chore] Bump version to 1.0.1 for development
  NimbleMedium.xcodeproj/project.pbxproj
Labels: type : chore

#132 [Chore] Fix build/archive failure on any iOS device
  .github/CODEOWNERS
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: type : chore

#134 [chore] Apply Resolver library for DI
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NimbleMedium/Sources/Application/App.swift
  NimbleMedium/Sources/Factories/Application/DependencyFactory+UseCaseFactoryProtocol.swift
  NimbleMedium/Sources/Factories/Application/DependencyFactory+ViewModelFactoryProtocol.swift
  NimbleMedium/Sources/Factories/Application/DependencyFactory.swift
  NimbleMedium/Sources/Factories/Data/RepositoryFactoryProtocol.swift
  NimbleMedium/Sources/Factories/Domain/UseCaseFactoryProtocol.swift
  NimbleMedium/Sources/Factories/Presentation/ViewModelFactoryProtocol.swift
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
  NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
  NimbleMedium/Sources/Presentation/Modules/Home/HomeViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Login/LoginView.swift
  NimbleMedium/Sources/Presentation/Modules/Login/LoginViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuMain/SideMenuView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuMain/SideMenuViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Signup/SignupView.swift
  NimbleMedium/Sources/Presentation/Modules/Signup/SignupViewModel.swift
  NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/Login/LoginViewModelSpec.swift
Labels: type : chore

#136 [Chore] Fix production CI failure
  .github/workflows/deploy_staging.yml
  .github/workflows/deploy_testflight.yml
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  NimbleMedium/Resources/Assets.xcassets/AppIcon.appiconset/iTunesArtwork@3x-1024.png
  NimbleMedium/Resources/Assets.xcassets/AppIcon.appiconset/iTunesArtwork@3x-20.png
  NimbleMedium/Resources/Assets.xcassets/AppIcon.appiconset/iTunesArtwork@3x-20@2x.png
  NimbleMedium/Resources/Assets.xcassets/AppIcon.appiconset/iTunesArtwork@3x-20@3x.png
  NimbleMedium/Resources/Assets.xcassets/AppIcon.appiconset/iTunesArtwork@3x-29.png
  NimbleMedium/Resources/Assets.xcassets/AppIcon.appiconset/iTunesArtwork@3x-29@2x.png
  NimbleMedium/Resources/Assets.xcassets/AppIcon.appiconset/iTunesArtwork@3x-29@3x.png
  NimbleMedium/Resources/Assets.xcassets/AppIcon.appiconset/iTunesArtwork@3x-40.png
  NimbleMedium/Resources/Assets.xcassets/AppIcon.appiconset/iTunesArtwork@3x-40@2x.png
  NimbleMedium/Resources/Assets.xcassets/AppIcon.appiconset/iTunesArtwork@3x-40@3x.png
  NimbleMedium/Resources/Assets.xcassets/AppIcon.appiconset/iTunesArtwork@3x-60@2x.png
  NimbleMedium/Resources/Assets.xcassets/AppIcon.appiconset/iTunesArtwork@3x-60@3x.png
  NimbleMedium/Resources/Assets.xcassets/AppIcon.appiconset/iTunesArtwork@3x-76.png
  NimbleMedium/Resources/Assets.xcassets/AppIcon.appiconset/iTunesArtwork@3x-76@2x.png
  NimbleMedium/Resources/Assets.xcassets/AppIcon.appiconset/iTunesArtwork@3x-83.5@2x.png
  fastlane/Constants/Constants.rb
  fastlane/Constants/Environments.rb
  fastlane/Fastfile
  fastlane/Managers/BuildManager.rb
  fastlane/Managers/DistributionManager.rb
  fastlane/Managers/MatchManager.rb
  fastlane/Managers/TestManager.rb
Labels: type : chore

#142 [chore] Bump version to 1.1.0 for development
  NimbleMedium.xcodeproj/project.pbxproj
Labels: type : chore

#133 [#17] [Integrate] As a user, I can see the global feeds from the home screen when not logged in
  .sourcery.yml
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Data/Models/CodableUser.swift
  NimbleMedium/Sources/Data/Models/DecodableArticle.swift
  NimbleMedium/Sources/Data/Models/DecodableProfile.swift
  NimbleMedium/Sources/Domain/Entities/Article.swift
  NimbleMedium/Sources/Domain/UseCases/ListArticlesUseCase.swift
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRow.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRowModel.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRowViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
  NimbleMedium/Sources/Supports/Extensions/Foundation/Date+Format.swift
  NimbleMedium/Sources/Supports/Extensions/Foundation/DateFormatter+Formats.swift
  NimbleMedium/Sources/Supports/Extensions/SwiftUI/View+Bind.swift
  NimbleMedium/Sources/Supports/Extensions/SwiftUI/View+OnReceive.swift
  NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedRow/FeedRowViewModelSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedsViewModelSpec.swift
  NimbleMediumTests/Sources/Utilities/PrimitiveSequenceType+TestScheduler.swift
Labels: priority : high, type : feature, category: integration

#144 [#38] As a user, I can see my profile briefing in the left menu header
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderView.swift
Labels: type : feature, category : ui

#135 [#19] [#75] As a user, I can see the article details screen when not logged in
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Resources/Assets.xcassets/Colors/Contents.json
  NimbleMedium/Resources/Assets.xcassets/Colors/Dark.colorset/Contents.json
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Constants/SystemImageName.swift
  NimbleMedium/Sources/Presentation/Modules/FeedDetail/FeedDetailView.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRow.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRowModel.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRowViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
  NimbleMedium/Sources/Presentation/Views/AppMainButton.swift
  NimbleMedium/Sources/Presentation/Views/AuthorView.swift
  NimbleMedium/Sources/Supports/Extensions/SwiftUI/View+If.swift
  NimbleMedium/Sources/Supports/Helpers/SwiftUI/NavigationBarPrimaryStyle.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedRow/FeedRowViewModelSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedsViewModelSpec.swift
Labels: priority : high, type : feature, category : ui

#137 [#22] [Backend] As a user, I can see an article details
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Data/NetworkAPI/Models/APIArticleResponse.swift
  NimbleMedium/Sources/Data/NetworkAPI/Models/APIArticlesResponse.swift
  NimbleMedium/Sources/Data/NetworkAPI/RequestConfigurations/ArticleRequestConfiguration.swift
  NimbleMedium/Sources/Data/Repositories/Article/ArticleRepository.swift
  NimbleMedium/Sources/Domain/Repositories/Article/ArticleRepositoryProtocol.swift
  NimbleMedium/Sources/Domain/UseCases/GetArticleUseCase.swift
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMediumTests/Resources/JSON/singleArticle.json
  NimbleMediumTests/Sources/Dummy/Data/Models/APIArticleResponse+Dummy.swift
  NimbleMediumTests/Sources/Dummy/Data/Models/APIArticlesResponse+Dummy.swift
  NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
  NimbleMediumTests/Sources/Specs/Data/Repositories/ArticleRepositorySpec.swift
  NimbleMediumTests/Sources/Specs/Domain/UseCases/GetArticleUseCaseSpec.swift
  NimbleMediumTests/Sources/Specs/Domain/UseCases/ListArticlesUseCaseSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedRow/FeedRowViewModelSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedsViewModelSpec.swift
  NimbleMediumTests/Sources/Utilities/Expectation+TestableObserver.swift
Labels: priority : high, category : backend

#147 [#40] As a user, I can view my profile details from the left menu
  NimbleMedium/Resources/Assets.xcassets/Menu/icon-my-profile.imageset/Contents.json
  NimbleMedium/Resources/Assets.xcassets/Menu/icon-my-profile.imageset/user.png
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift
Labels: type : feature, category : ui

#148 [#41] As a user, I can logout from the left menu
  NimbleMedium/Resources/Assets.xcassets/Menu/icon-logout.imageset/Contents.json
  NimbleMedium/Resources/Assets.xcassets/Menu/icon-logout.imageset/logout_icon_151219.png
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift
Labels: type : feature, category : ui

#146 [#53] As a user, I can see my profile briefing in the left menu header
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Data/Models/CodableUser.swift
  NimbleMedium/Sources/Data/Repositories/User/UserSessionRepository.swift
  NimbleMedium/Sources/Domain/Repositories/User/UserSessionRepositoryProtocol.swift
  NimbleMedium/Sources/Domain/UseCases/GetCurrentSessionUseCase.swift
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMedium/Sources/Presentation/Modules/Home/HomeViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderView+UIModel.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderViewModel.swift
  NimbleMediumTests/Sources/Dummy/Domain/Entities/UserDummy.swift
  NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/SideMenuHeader/SideMenuHeaderViewModelSpec.swift
  Podfile.lock
Labels: type : feature, category: integration

#138 [#56] [#21] [Integrate] As a user, I can see the article details screen when not logged in
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMedium/Sources/Presentation/Modules/FeedDetail/FeedDetailView+UIModel.swift
  NimbleMedium/Sources/Presentation/Modules/FeedDetail/FeedDetailView.swift
  NimbleMedium/Sources/Presentation/Modules/FeedDetail/FeedDetailViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRow+UIModel.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRow.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRowViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/FeedDetail/FeedDetailViewModelSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedRow/FeedRowViewModelSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedsViewModelSpec.swift
Labels: priority : high, category: integration

#139 [#103] [Backend] Add Get Comments API
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Data/NetworkAPI/Models/APIArticleComment.swift
  NimbleMedium/Sources/Data/NetworkAPI/Models/APIArticleCommentsResponse.swift
  NimbleMedium/Sources/Data/NetworkAPI/RequestConfigurations/ArticleCommentRequestConfiguration.swift
  NimbleMedium/Sources/Data/Repositories/ArticleComment/ArticleCommentRepository.swift
  NimbleMedium/Sources/Domain/Entities/ArticleComment.swift
  NimbleMedium/Sources/Domain/Repositories/ArticleComment/ArticleCommentRepositoryProtocol.swift
  NimbleMedium/Sources/Domain/UseCases/GetArticleCommentsUseCase.swift
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMediumTests/Resources/JSON/articleComments.json
  NimbleMediumTests/Sources/Dummy/Data/Models/APIArticleCommentsResponse+Dummy.swift
  NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
  NimbleMediumTests/Sources/Specs/Data/Repositories/ArticleCommentRepositorySpec.swift
  NimbleMediumTests/Sources/Specs/Domain/UseCases/GetArticleCommentsUseCaseSpec.swift
Labels: category : backend

#140 [#29] As a user, I see the list of comments of an article
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Resources/Assets.xcassets/Colors/LightGray.colorset/Contents.json
  NimbleMedium/Resources/Assets.xcassets/Colors/SemiLightGray.colorset/Contents.json
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentRow/FeedCommentRow.swift
  NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentsView.swift
Labels: type : feature, category : ui

#150 [#62] Implement UI for User Profile screen
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView+UIModel.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView.swift
Labels: type : feature, category : ui

#153 [chore] Bump version to 1.2.0 for development
  NimbleMedium.xcodeproj/project.pbxproj
Labels: priority : high, type : chore

#155 [#145] Fix: The left menu is still openable in Article Details screen by dragging the screen from left to right
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
Labels: type : bug

#156 [#63] As a user, I can get other author profile information
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Data/NetworkAPI/Models/APIProfileResponse.swift
  NimbleMedium/Sources/Data/NetworkAPI/RequestConfigurations/UserRequestConfiguration.swift
  NimbleMedium/Sources/Data/Repositories/User/UserRepository.swift
  NimbleMedium/Sources/Domain/Repositories/Comment/ArticleCommentRepositoryProtocol.swift
  NimbleMedium/Sources/Domain/Repositories/User/UserRepositoryProtocol.swift
  NimbleMedium/Sources/Domain/UseCases/Article/GetArticleUseCase.swift
  NimbleMedium/Sources/Domain/UseCases/Article/ListArticlesUseCase.swift
  NimbleMedium/Sources/Domain/UseCases/Auth/LoginUseCase.swift
  NimbleMedium/Sources/Domain/UseCases/Auth/SignupUseCase.swift
  NimbleMedium/Sources/Domain/UseCases/Comment/GetArticleCommentsUseCase.swift
  NimbleMedium/Sources/Domain/UseCases/User/GetCurrentSessionUseCase.swift
  NimbleMedium/Sources/Domain/UseCases/User/GetUserProfileUseCase.swift
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMediumTests/Resources/JSON/profile.json
  NimbleMediumTests/Sources/Dummy/Data/Models/APIProfileResponse+Dummy.swift
  NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
  NimbleMediumTests/Sources/Specs/Data/Repositories/Article/ArticleRepositorySpec.swift
  NimbleMediumTests/Sources/Specs/Data/Repositories/Comment/ArticleCommentRepositorySpec.swift
  NimbleMediumTests/Sources/Specs/Domain/UseCases/Article/GetArticleUseCaseSpec.swift
  NimbleMediumTests/Sources/Specs/Domain/UseCases/Article/ListArticlesUseCaseSpec.swift
  NimbleMediumTests/Sources/Specs/Domain/UseCases/Comment/GetArticleCommentsUseCaseSpec.swift
  NimbleMediumTests/Sources/Specs/Domain/UseCases/User/GetUserProfileUseCaseSpec.swift
Labels: type : feature, category : backend

#157 [#70] As a user, I can see the list of favorited articles from the profile screen
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Domain/UseCases/Article/GetFavouritedArticlesUseCase.swift
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMediumTests/Sources/Specs/Domain/UseCases/Article/GetFavouritedArticlesUseCaseSpec.swift
Labels: category : backend

#158 [Chore] Refactor ListArticlesUseCase
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Domain/UseCases/Article/GetListArticlesUseCase.swift
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
  NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
  NimbleMediumTests/Sources/Specs/Domain/UseCases/Article/GetListArticlesUseCaseSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/FeedComments/FeedCommentRow/FeedCommentRowViewModelSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedRow/FeedRowViewModelSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedsViewModelSpec.swift
Labels: type : chore

#160 [#161] Disable support for dark mode since the app doesn't handle it yet
  NimbleMedium/Configurations/Plists/Info.plist
Labels: priority : high, type : bug
