Repository nimblehq/nimble-medium-ios, pull requests merged in 2021-11, with the labels that each got.

#214 [#91] As a user, I can delete my article from the article details screen
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Constants/SystemImageName.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift
Labels: category : ui

#215 [#94] As a user, I can delete my article from the article details screen
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsTab/FeedsTabView.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
  NimbleMediumTests/Sources/Dummy/Data/Models/APIUserResponse+Dummy.swift
  NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/ArticleDetail/ArticleDetailViewModelSpec.swift
  NimbleMediumTests/Sources/Utilities/String+Data.swift
Labels: category: integration

#217 [#95] As a user, I can edit my article from the article details screen
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift
Labels: category : ui

#218 [#86][#48] Add Favourite Button UI
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Constants/SystemImageName.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/ArticleRow/ArticleRow.swift
  NimbleMedium/Sources/Presentation/Views/FavouriteButton.swift
Labels: category : ui

#219 [#49] Add Favourite Button UI in Article Detail screen
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift
Labels: category : ui

#216 [#96] As a user, I can edit my own article
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Presentation/Modules/CreateArticle/CreateArticleView.swift
  NimbleMedium/Sources/Presentation/Modules/EditArticle/EditArticleView.swift
  NimbleMedium/Sources/Presentation/Views/ArticleInputFields/ArticleInputFields.swift
  NimbleMedium/Sources/Presentation/Views/ArticleInputFields/FieldType.swift
Labels: type : feature, category : ui

#220 [#88] [#90] As a user, I can toggle to update an article as my favorites from the home/profile screen
  NimbleMedium/Sources/Presentation/Modules/Feeds/ArticleRow/ArticleRow+UIModel.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/ArticleRow/ArticleRow.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/ArticleRow/ArticleRowViewModel.swift
  NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/ArticleRow/ArticleRowViewModelSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedsTab/FeedsTabViewModelSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedsViewModelSpec.swift
Labels: category: integration

#221 [#89] Integrate Favourite Button in Article Detail screen
  NimbleMedium/Sources/Constants/SystemImageName.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView+UIModel.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailViewModel.swift
  NimbleMedium/Sources/Supports/Extensions/SwiftUI/View+OnReceive.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/ArticleDetail/ArticleDetailViewModelSpec.swift
Labels: category: integration

#222 [#208] Fix: Home screen won't update tabs when a user login/logout
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Application/App.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Shared/UserSessionViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModel.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedsViewModelSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/Shared/UserSessionViewModelSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModelSpec.swift
Labels: priority : high, type : bug

#223 [#98] As a user, I can edit my article from the article details screen
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift
Labels: category: integration

#224 [#99] As a user, I can edit my own article
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/EditArticle/EditArticleView+UIModel.swift
  NimbleMedium/Sources/Presentation/Modules/EditArticle/EditArticleView.swift
  NimbleMedium/Sources/Presentation/Modules/EditArticle/EditArticleViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsTab/FeedsTabView.swift
  NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/EditArticle/EditArticleViewModelSpec.swift
Labels: category: integration

#225 [#100] As a user, I can comment on an article in the comments history screen
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Constants/SystemImageName.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentsView.swift
Labels: category : ui

#227 [#226] Fix: Keyboard dismiss after typing a character when create/edit article detail
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Presentation/Modules/CreateArticle/CreateArticleView.swift
  NimbleMedium/Sources/Presentation/Modules/EditArticle/EditArticleView.swift
  NimbleMedium/Sources/Presentation/Views/ArticleInputFields/ArticleInputFields.swift
  NimbleMedium/Sources/Presentation/Views/ArticleInputFields/FieldType.swift
Labels: priority : high, type : bug

#228 [#106] As a user, I can delete my comment on an article in the comments history screen
  NimbleMedium/Sources/Constants/SystemImageName.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentRow/ArticleCommentRow.swift
Labels: type : feature, category : ui

#229 [#104] As a user, I can comment on an article in the comments history screen
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentsView.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentsViewModel.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/ArticleComments/ArticleCommentsViewModelSpec.swift
Labels: category: integration

#235 [#108] As a user, I can delete my comment on an article in the comments history screen
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentRow/ArticleCommentRow+UIModel.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentRow/ArticleCommentRow.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentRow/ArticleCommentRowViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentsViewModel.swift
  NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/ArticleComments/FeedCommentRow/ArticleCommentRowViewModelSpec.swift
Labels: category: integration

#234 [chore] Bump version to 1.4.1 for development
  NimbleMedium.xcodeproj/project.pbxproj
Labels: priority : high, type : chore

#239 [#238] Chore: Refactor Resolver library scope correctly for ViewModel
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
Labels: type : chore, priority : medium

#240 [#237] Refactor Resolve library to register correctly
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
Labels: type : chore, priority : medium

#246 [#243] Fix: Username & Email input got uppercase in the first letter in Login & Signup screen
  NimbleMedium/Sources/Presentation/Modules/Login/LoginView.swift
  NimbleMedium/Sources/Presentation/Modules/Signup/SignupView.swift
  NimbleMedium/Sources/Presentation/Views/AppTextField.swift
Labels: priority : low, type : bug

#241 [#232] Verify backend stability
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Constants/Constants+API.swift
  NimbleMedium/Sources/Data/NetworkAPI/Core/AuthenticatedNetworkAPI.swift
  NimbleMedium/Sources/Data/NetworkAPI/Core/NetworkAPI.swift
  NimbleMedium/Sources/Data/NetworkAPI/Interceptors/CommonInterceptor.swift
Labels: type : chore

#247 [#245] Fix: Home screen doesn't refresh
  NimbleMedium.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsTab/FeedsTabView.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
Labels: type : bug

#248 [#233] Fix: Menu swipe from left behavior doesn't work very smooth
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
  NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
  NimbleMedium/Sources/Presentation/Modules/Home/SideMenuDraggingAnimator.swift
Labels: type : bug

#249 [#244] As a user, I want to see the input label when it's filled in Create & Edit Article screen
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Presentation/Modules/CreateArticle/CreateArticleView.swift
  NimbleMedium/Sources/Presentation/Modules/EditArticle/EditArticleView.swift
  NimbleMedium/Sources/Presentation/Views/LabeledAppTextField.swift
  NimbleMedium/Sources/Presentation/Views/LabeledAppTextView.swift
Labels: type : feature, category : ui

#252 [#242] Handle token expired while using the application
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Application/NimbleMediumApp+Firebase.swift
  NimbleMedium/Sources/Application/NimbleMediumApp+NetworkLogger.swift
  NimbleMedium/Sources/Application/NimbleMediumApp.swift
  NimbleMedium/Sources/Data/NetworkAPI/Constants/HTTPStatusCode.swift
  NimbleMedium/Sources/Data/NetworkAPI/Core/NetworkAPIProtocol.swift
  NimbleMedium/Sources/Data/NetworkAPI/Interceptors/AuthenticatedInterceptor.swift
  NimbleMedium/Sources/Domain/UseCases/Article/GetCurrentUserFollowingArticlesUseCase.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentRow/ArticleCommentRow.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentsView.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift
  NimbleMedium/Sources/Presentation/Modules/CreateArticle/CreateArticleView.swift
  NimbleMedium/Sources/Presentation/Modules/EditArticle/EditArticleView.swift
  NimbleMedium/Sources/Presentation/Modules/EditProfile/EditProfileView.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/ArticleRow/ArticleRow.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsTab/FeedsTabView.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
  NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
  NimbleMedium/Sources/Presentation/Modules/Home/HomeViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Login/LoginView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Signup/SignupView.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/CreatedArticlesTab/UserProfileCreatedArticlesTab.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/FavourtiedArticlesTab/UserProfileFavouritedArticlesTab.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView.swift
  NimbleMedium/Sources/Supports/Helpers/SwiftUI/NavigationBarPrimaryStyle.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModelSpec.swift
Labels: type : feature

#255 [#251] Fix: Cannot load created articles and my favorited articles in my profile screen
  NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileViewModel.swift
Labels: type : bug

#254 [#250] Fix: Comment is not cleared after sending successfully and keyboard got dismissed when sending
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentsView.swift
  NimbleMedium/Sources/Presentation/Views/AppTextView.swift
  NimbleMedium/Sources/Presentation/Views/LabeledAppTextView.swift
Labels: type : bug

#258 Release/1.4.1
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Application/NimbleMediumApp+Firebase.swift
  NimbleMedium/Sources/Application/NimbleMediumApp+NetworkLogger.swift
  NimbleMedium/Sources/Application/NimbleMediumApp.swift
  NimbleMedium/Sources/Constants/Constants+API.swift
  NimbleMedium/Sources/Data/NetworkAPI/Constants/HTTPStatusCode.swift
  NimbleMedium/Sources/Data/NetworkAPI/Core/AuthenticatedNetworkAPI.swift
  NimbleMedium/Sources/Data/NetworkAPI/Core/NetworkAPI.swift
  NimbleMedium/Sources/Data/NetworkAPI/Core/NetworkAPIProtocol.swift
  NimbleMedium/Sources/Data/NetworkAPI/Interceptors/AuthenticatedInterceptor.swift
  NimbleMedium/Sources/Data/NetworkAPI/Interceptors/CommonInterceptor.swift
  NimbleMedium/Sources/Domain/UseCases/Article/GetCurrentUserFollowingArticlesUseCase.swift
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentRow/ArticleCommentRow.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentsView.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift
  NimbleMedium/Sources/Presentation/Modules/CreateArticle/CreateArticleView.swift
  NimbleMedium/Sources/Presentation/Modules/EditArticle/EditArticleView.swift
  NimbleMedium/Sources/Presentation/Modules/EditProfile/EditProfileView.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/ArticleRow/ArticleRow.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsTab/FeedsTabView.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
  NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
  NimbleMedium/Sources/Presentation/Modules/Home/HomeViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Home/SideMenuDraggingAnimator.swift
  NimbleMedium/Sources/Presentation/Modules/Login/LoginView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Signup/SignupView.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/CreatedArticlesTab/UserProfileCreatedArticlesTab.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/FavourtiedArticlesTab/UserProfileFavouritedArticlesTab.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileViewModel.swift
  NimbleMedium/Sources/Presentation/Views/AppTextField.swift
  NimbleMedium/Sources/Presentation/Views/AppTextView.swift
  NimbleMedium/Sources/Presentation/Views/LabeledAppTextField.swift
  NimbleMedium/Sources/Presentation/Views/LabeledAppTextView.swift
  NimbleMedium/Sources/Supports/Helpers/SwiftUI/NavigationBarPrimaryStyle.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModelSpec.swift
Labels: type : release

#253 [#230] Fix: Check danger comments on pull request #230
  .github/workflows/automatic_pull_request_review.yml
  .swiftlint.yml
  Gemfile
  Gemfile.lock
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium.xcodeproj/xcshareddata/xcschemes/NimbleMedium Staging.xcscheme
  NimbleMedium.xcodeproj/xcshareddata/xcschemes/NimbleMedium.xcscheme
  NimbleMediumUITests/NimbleMediumUITests.swift
  NimbleMediumUITests/Sources/Specs/ApplicationSpec.swift
  Podfile
  Podfile.lock
  fastlane/Constants/Constants.rb
  fastlane/Fastfile
  fastlane/Managers/ReportManager.rb
  fastlane/Managers/TestManager.rb
Labels: type : bug

#259 [chore] Bump version to 1.4.2 for development
  NimbleMedium.xcodeproj/project.pbxproj
Labels: priority : high, type : chore

#257 [#256] Fix: Unable to install staging version
  .github/workflows/deploy_staging.yml
  .github/workflows/deploy_testflight.yml
  .slather.yml
  Gemfile
  Gemfile.lock
Labels: type : bug

#262 [#261] Fix: Sign up button doesn't work
  NimbleMedium/Sources/Presentation/Modules/EditProfile/EditProfileView.swift
  NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift
  Podfile.lock
Labels: priority : high, type : bug

#266 [#264] Fix: Align article contents to the left for small contents in Article screen
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift
Labels: type : bug

#268 [#267] Clear Xcode warnings cause code is out of update
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
  Podfile.lock
Labels: type : chore

#265 [#260] Fix: Favorite button doesn't update correctly on Home Screen
  NimbleMedium/Sources/Data/NetworkAPI/Interceptors/AuthenticatedInterceptor.swift
  NimbleMedium/Sources/Data/Repositories/Article/ArticleRepository.swift
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView+UIModel.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/ArticleRow/ArticleRow+UIModel.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/ArticleRow/ArticleRowViewModel.swift
  NimbleMediumTests/Sources/Specs/Data/Repositories/Article/ArticleRepositorySpec.swift
Labels: type : bug

#269 [#263] Rename "favourite" to "favorite"
  NimbleMedium.xcodeproj/project.pbxproj
  NimbleMedium/Resources/en.lproj/Localizable.strings
  NimbleMedium/Sources/Domain/UseCases/Article/GetFavoritedArticlesUseCase.swift
  NimbleMedium/Sources/Injection/Resolver+Injection.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift
  NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/ArticleRow/ArticleRow.swift
  NimbleMedium/Sources/Presentation/Modules/Feeds/ArticleRow/ArticleRowViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/FavortiedArticlesTab/UserProfileFavoritedArticlesTab.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/FavortiedArticlesTab/UserProfileFavoritedArticlesTabViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/FavourtiedArticlesTab/UserProfileFavouritedArticlesTabViewModel.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView.swift
  NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileViewModel.swift
  NimbleMedium/Sources/Presentation/Views/FavoriteButton.swift
  NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
  NimbleMediumTests/Sources/Specs/Domain/UseCases/Article/GetFavoritedArticlesUseCaseSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/ArticleDetail/ArticleDetailViewModelSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/ArticleRow/ArticleRowViewModelSpec.swift
  NimbleMediumTests/Sources/Specs/Presentation/Modules/UserProfile/FavoritedArticlesTab/UserProfileFavoritedArticlesTabViewModelSpec.swift
Labels: type : chore
